//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class AddressType
    {
        public AddressType()
        {
            this.PersonAddresses = new HashSet<PersonAddress>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool WithoutEndDate { get; set; }
        public int PriorityForOKATO { get; set; }
    
        [NonSerialized]
    	private ICollection<PersonAddress> personAddresses;
    
    	public virtual ICollection<PersonAddress> PersonAddresses
    	{
     		get { return personAddresses; }
     		set { personAddresses = value; }
    	}
    }
}
