//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class AnalyseRefference
    {
        public int Id { get; set; }
        public int RecordTypeId { get; set; }
        public int ParameterRecordTypeId { get; set; }
        public bool IsMale { get; set; }
        public int AgeFrom { get; set; }
        public Nullable<int> AgeTo { get; set; }
        public double RefMin { get; set; }
        public double RefMax { get; set; }
    
        [NonSerialized]
    	private RecordType recordType;
    
    	public virtual RecordType RecordType
    	{
     		get { return recordType; }
     		set { recordType = value; }
    	}
        [NonSerialized]
    	private RecordType recordType1;
    
    	public virtual RecordType RecordType1
    	{
     		get { return recordType1; }
     		set { recordType1 = value; }
    	}
    }
}
