//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Branch
    {
        public Branch()
        {
            this.Branches1 = new HashSet<Branch>();
            this.PersonStaffs = new HashSet<PersonStaff>();
            this.Eqiupments = new HashSet<Eqiupment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
    
        [NonSerialized]
    	private ICollection<Branch> branches1;
    
    	public virtual ICollection<Branch> Branches1
    	{
     		get { return branches1; }
     		set { branches1 = value; }
    	}
        [NonSerialized]
    	private Branch branch1;
    
    	public virtual Branch Branch1
    	{
     		get { return branch1; }
     		set { branch1 = value; }
    	}
        [NonSerialized]
    	private ICollection<PersonStaff> personStaffs;
    
    	public virtual ICollection<PersonStaff> PersonStaffs
    	{
     		get { return personStaffs; }
     		set { personStaffs = value; }
    	}
        [NonSerialized]
    	private ICollection<Eqiupment> eqiupments;
    
    	public virtual ICollection<Eqiupment> Eqiupments
    	{
     		get { return eqiupments; }
     		set { eqiupments = value; }
    	}
    }
}
