//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class ColorsSetting : ICloneable
    {
        public ColorsSetting()
        {
            this.Decisions = new HashSet<Decision>();
        }
    
        public int Id { get; set; }
        public string ColorName { get; set; }
        public string Options { get; set; }
        public string Description { get; set; }
        public string Hex { get; set; }
    
        [NonSerialized]
    	protected ICollection<Decision> decisions;
    
    	public virtual ICollection<Decision> Decisions
    	{
     		get { return decisions; }
     		set { decisions = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
