//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class CommissionMemberType : ICloneable
    {
        public CommissionMemberType()
        {
            this.CommissionDecisionsLinks = new HashSet<CommissionDecisionsLink>();
            this.CommissionMembers = new HashSet<CommissionMember>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public bool IsChief { get; set; }
        public bool IsSecretary { get; set; }
        public bool IsMember { get; set; }
    
        [NonSerialized]
    	protected ICollection<CommissionDecisionsLink> commissionDecisionsLinks;
    
    	public virtual ICollection<CommissionDecisionsLink> CommissionDecisionsLinks
    	{
     		get { return commissionDecisionsLinks; }
     		set { commissionDecisionsLinks = value; }
    	}
        [NonSerialized]
    	protected ICollection<CommissionMember> commissionMembers;
    
    	public virtual ICollection<CommissionMember> CommissionMembers
    	{
     		get { return commissionMembers; }
     		set { commissionMembers = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
