//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class CommissionQuestion : ICloneable
    {
        public CommissionQuestion()
        {
            this.CommissionDecisionsLinks = new HashSet<CommissionDecisionsLink>();
            this.CommissionProtocols = new HashSet<CommissionProtocol>();
        }
    
        public int Id { get; set; }
        public int CommissionTypeId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> PrintedDocumentId { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
    
        [NonSerialized]
    	protected ICollection<CommissionDecisionsLink> commissionDecisionsLinks;
    
    	public virtual ICollection<CommissionDecisionsLink> CommissionDecisionsLinks
    	{
     		get { return commissionDecisionsLinks; }
     		set { commissionDecisionsLinks = value; }
    	}
        [NonSerialized]
    	protected CommissionType commissionType;
    
    	public virtual CommissionType CommissionType
    	{
     		get { return commissionType; }
     		set { commissionType = value; }
    	}
        [NonSerialized]
    	protected ICollection<CommissionProtocol> commissionProtocols;
    
    	public virtual ICollection<CommissionProtocol> CommissionProtocols
    	{
     		get { return commissionProtocols; }
     		set { commissionProtocols = value; }
    	}
        [NonSerialized]
    	protected PrintedDocument printedDocument;
    
    	public virtual PrintedDocument PrintedDocument
    	{
     		get { return printedDocument; }
     		set { printedDocument = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
