//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class CommissionMember
    {
        public CommissionMember()
        {
            this.CommissionDecisions = new HashSet<CommissionDecision>();
            this.CommissionDecisions1 = new HashSet<CommissionDecision>();
        }
    
        public int Id { get; set; }
        public int PersonStaffId { get; set; }
        public int CommissionMemberTypeId { get; set; }
        public int CommissionTypeId { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
    
        [NonSerialized]
    	private ICollection<CommissionDecision> commissionDecisions;
    
    	public virtual ICollection<CommissionDecision> CommissionDecisions
    	{
     		get { return commissionDecisions; }
     		set { commissionDecisions = value; }
    	}
        [NonSerialized]
    	private ICollection<CommissionDecision> commissionDecisions1;
    
    	public virtual ICollection<CommissionDecision> CommissionDecisions1
    	{
     		get { return commissionDecisions1; }
     		set { commissionDecisions1 = value; }
    	}
        [NonSerialized]
    	private CommissionMemberType commissionMemberType;
    
    	public virtual CommissionMemberType CommissionMemberType
    	{
     		get { return commissionMemberType; }
     		set { commissionMemberType = value; }
    	}
        [NonSerialized]
    	private CommissionType commissionType;
    
    	public virtual CommissionType CommissionType
    	{
     		get { return commissionType; }
     		set { commissionType = value; }
    	}
        [NonSerialized]
    	private PersonStaff personStaff;
    
    	public virtual PersonStaff PersonStaff
    	{
     		get { return personStaff; }
     		set { personStaff = value; }
    	}
    }
}
