//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class CommissionType
    {
        public CommissionType()
        {
            this.CommissionDecisionsLinks = new HashSet<CommissionDecisionsLink>();
            this.CommissionMembers = new HashSet<CommissionMember>();
            this.CommissionQuestions = new HashSet<CommissionQuestion>();
            this.CommissionSources = new HashSet<CommissionSource>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
    
        [NonSerialized]
    	private ICollection<CommissionDecisionsLink> commissionDecisionsLinks;
    
    	public virtual ICollection<CommissionDecisionsLink> CommissionDecisionsLinks
    	{
     		get { return commissionDecisionsLinks; }
     		set { commissionDecisionsLinks = value; }
    	}
        [NonSerialized]
    	private ICollection<CommissionMember> commissionMembers;
    
    	public virtual ICollection<CommissionMember> CommissionMembers
    	{
     		get { return commissionMembers; }
     		set { commissionMembers = value; }
    	}
        [NonSerialized]
    	private ICollection<CommissionQuestion> commissionQuestions;
    
    	public virtual ICollection<CommissionQuestion> CommissionQuestions
    	{
     		get { return commissionQuestions; }
     		set { commissionQuestions = value; }
    	}
        [NonSerialized]
    	private ICollection<CommissionSource> commissionSources;
    
    	public virtual ICollection<CommissionSource> CommissionSources
    	{
     		get { return commissionSources; }
     		set { commissionSources = value; }
    	}
    }
}
