//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class CommissionDecisionsLink
    {
        public int Id { get; set; }
        public int CommissionTypeId { get; set; }
        public int CommissionTypeMemberId { get; set; }
        public int DecisionId { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
    
        [NonSerialized]
    	private CommissionMemberType commissionMemberType;
    
    	public virtual CommissionMemberType CommissionMemberType
    	{
     		get { return commissionMemberType; }
     		set { commissionMemberType = value; }
    	}
        [NonSerialized]
    	private CommissionType commissionType;
    
    	public virtual CommissionType CommissionType
    	{
     		get { return commissionType; }
     		set { commissionType = value; }
    	}
        [NonSerialized]
    	private Decision decision;
    
    	public virtual Decision Decision
    	{
     		get { return decision; }
     		set { decision = value; }
    	}
    }
}
