//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Complication : ICloneable
    {
        public Complication()
        {
            this.Complications1 = new HashSet<Complication>();
            this.Diagnoses = new HashSet<Diagnosis>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string Options { get; set; }
    
        [NonSerialized]
    	protected ICollection<Complication> complications1;
    
    	public virtual ICollection<Complication> Complications1
    	{
     		get { return complications1; }
     		set { complications1 = value; }
    	}
        [NonSerialized]
    	protected Complication complication1;
    
    	public virtual Complication Complication1
    	{
     		get { return complication1; }
     		set { complication1 = value; }
    	}
        [NonSerialized]
    	protected ICollection<Diagnosis> diagnoses;
    
    	public virtual ICollection<Diagnosis> Diagnoses
    	{
     		get { return diagnoses; }
     		set { diagnoses = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
