//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Country : ICloneable
    {
        public Country()
        {
            this.PersonNationalities = new HashSet<PersonNationality>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsDefaultNationality { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
    
        [NonSerialized]
    	protected ICollection<PersonNationality> personNationalities;
    
    	public virtual ICollection<PersonNationality> PersonNationalities
    	{
     		get { return personNationalities; }
     		set { personNationalities = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
