//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DecisionKind : ICloneable
    {
        public DecisionKind()
        {
            this.Decisions = new HashSet<Decision>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Type { get; set; }
        public int ColorSettingsId { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
    
        [NonSerialized]
    	protected ColorsSetting colorsSetting;
    
    	public virtual ColorsSetting ColorsSetting
    	{
     		get { return colorsSetting; }
     		set { colorsSetting = value; }
    	}
        [NonSerialized]
    	protected ICollection<Decision> decisions;
    
    	public virtual ICollection<Decision> Decisions
    	{
     		get { return decisions; }
     		set { decisions = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
