
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Core.Data
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class DefaultProtocol : ICloneable
{

    public int Id { get; set; }

    public int RecordId { get; set; }

    public string Description { get; set; }

    public string Conclusion { get; set; }



    [NonSerialized]
    	protected Record record;
    
    	public virtual Record Record
    	{
     		get { return record; }
     		set { record = value; }
    	}


	public object Clone()
	{
		return MemberwiseClone();
	}
}

}
