//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosis
    {
        public int Id { get; set; }
        public int PersonDiagnosId { get; set; }
        public int DiagnosLevelId { get; set; }
        public string DiagnosText { get; set; }
        public string MKB { get; set; }
        public Nullable<int> ComplicationId { get; set; }
        public bool IsMainDiagnos { get; set; }
        public string Options { get; set; }
        public System.DateTime InDateTime { get; set; }
        public int InPersonId { get; set; }
    
        public virtual Complication Complication { get; set; }
        public virtual DiagnosLevel DiagnosLevel { get; set; }
        public virtual PersonDiagnos PersonDiagnos { get; set; }
        public virtual Person Person { get; set; }
    }
}
