//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DiagnosLevel
    {
        public DiagnosLevel()
        {
            this.Diagnoses = new HashSet<Diagnosis>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public int Priority { get; set; }
        public bool IsActual { get; set; }
        public bool HasMKB { get; set; }
        public bool IsComplication { get; set; }
    
        [NonSerialized]
    	private ICollection<Diagnosis> diagnoses;
    
    	public virtual ICollection<Diagnosis> Diagnoses
    	{
     		get { return diagnoses; }
     		set { diagnoses = value; }
    	}
    }
}
