//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DiagnosType : ICloneable
    {
        public DiagnosType()
        {
            this.PersonDiagnoses = new HashSet<PersonDiagnos>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Priority { get; set; }
        public bool IsActual { get; set; }
        public bool AllowCopy { get; set; }
        public bool HasComplications { get; set; }
        public bool NeedSetMainDiagnos { get; set; }
        public string MainDiagnosHeader { get; set; }
        public string Options { get; set; }
    
        [NonSerialized]
    	protected ICollection<PersonDiagnos> personDiagnoses;
    
    	public virtual ICollection<PersonDiagnos> PersonDiagnoses
    	{
     		get { return personDiagnoses; }
     		set { personDiagnoses = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
