//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DisabilityType : ICloneable
    {
        public DisabilityType()
        {
            this.PersonDisabilities = new HashSet<PersonDisability>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        [NonSerialized]
    	protected ICollection<PersonDisability> personDisabilities;
    
    	public virtual ICollection<PersonDisability> PersonDisabilities
    	{
     		get { return personDisabilities; }
     		set { personDisabilities = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
