
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Core.Data
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class Document : ICloneable
{

    public Document()
    {

        this.PersonOuterDocuments = new HashSet<PersonOuterDocument>();

        this.Persons = new HashSet<Person>();

        this.RecordDocuments = new HashSet<RecordDocument>();

    }


    public int Id { get; set; }

    public string FileName { get; set; }

    public string DisplayName { get; set; }

    public string Extension { get; set; }

    public byte[] FileData { get; set; }

    public long FileSize { get; set; }

    public System.DateTime UploadDate { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> DocumentFromDate { get; set; }




    [NonSerialized]
    	protected ICollection<PersonOuterDocument> personOuterDocuments;
    
    	public virtual ICollection<PersonOuterDocument> PersonOuterDocuments
    	{
     		get { return personOuterDocuments; }
     		set { personOuterDocuments = value; }
    	}


    [NonSerialized]
    	protected ICollection<Person> persons;
    
    	public virtual ICollection<Person> Persons
    	{
     		get { return persons; }
     		set { persons = value; }
    	}


    [NonSerialized]
    	protected ICollection<RecordDocument> recordDocuments;
    
    	public virtual ICollection<RecordDocument> RecordDocuments
    	{
     		get { return recordDocuments; }
     		set { recordDocuments = value; }
    	}


	public object Clone()
	{
		return MemberwiseClone();
	}
}

}
