//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eqiupment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eqiupment()
        {
            this.RecordEquipments = new HashSet<RecordEquipment>();
        }
    
        public int Id { get; set; }
        public int EquipmentTypeId { get; set; }
        public string Name { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string CatalogNumber { get; set; }
        public string NameToEconomics { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public System.DateTime StartUseDate { get; set; }
        public System.DateTime EndUseDate { get; set; }
        public string SertificateNumber { get; set; }
        public string InventoryNumber { get; set; }
        public string PhotoPath { get; set; }
        public string IPAddress { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual EqiupmentType EqiupmentType { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecordEquipment> RecordEquipments { get; set; }
    }
}
