
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Core.Data
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class Eqiupment : ICloneable
{

    public Eqiupment()
    {

        this.RecordEquipments = new HashSet<RecordEquipment>();

    }


    public int Id { get; set; }

    public int EquipmentTypeId { get; set; }

    public string Name { get; set; }

    public Nullable<int> RoomId { get; set; }

    public Nullable<int> BranchId { get; set; }

    public string CatalogNumber { get; set; }

    public string NameToEconomics { get; set; }

    public System.DateTime ProductionDate { get; set; }

    public System.DateTime StartUseDate { get; set; }

    public System.DateTime EndUseDate { get; set; }

    public string SertificateNumber { get; set; }

    public string InventoryNumber { get; set; }

    public string PhotoPath { get; set; }

    public string IPAddress { get; set; }



    [NonSerialized]
    	protected Branch branch;
    
    	public virtual Branch Branch
    	{
     		get { return branch; }
     		set { branch = value; }
    	}

    [NonSerialized]
    	protected EqiupmentType eqiupmentType;
    
    	public virtual EqiupmentType EqiupmentType
    	{
     		get { return eqiupmentType; }
     		set { eqiupmentType = value; }
    	}

    [NonSerialized]
    	protected Room room;
    
    	public virtual Room Room
    	{
     		get { return room; }
     		set { room = value; }
    	}


    [NonSerialized]
    	protected ICollection<RecordEquipment> recordEquipments;
    
    	public virtual ICollection<RecordEquipment> RecordEquipments
    	{
     		get { return recordEquipments; }
     		set { recordEquipments = value; }
    	}


	public object Clone()
	{
		return MemberwiseClone();
	}
}

}
