//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class FinancingSource : ICloneable
    {
        public FinancingSource()
        {
            this.Assignments = new HashSet<Assignment>();
            this.RecordContracts = new HashSet<RecordContract>();
            this.RecordTypeCosts = new HashSet<RecordTypeCost>();
            this.Visits = new HashSet<Visit>();
            this.VisitTemplates = new HashSet<VisitTemplate>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public bool IsActive { get; set; }
        public string Options { get; set; }
    
        [NonSerialized]
    	protected ICollection<Assignment> assignments;
    
    	public virtual ICollection<Assignment> Assignments
    	{
     		get { return assignments; }
     		set { assignments = value; }
    	}
        [NonSerialized]
    	protected ICollection<RecordContract> recordContracts;
    
    	public virtual ICollection<RecordContract> RecordContracts
    	{
     		get { return recordContracts; }
     		set { recordContracts = value; }
    	}
        [NonSerialized]
    	protected ICollection<RecordTypeCost> recordTypeCosts;
    
    	public virtual ICollection<RecordTypeCost> RecordTypeCosts
    	{
     		get { return recordTypeCosts; }
     		set { recordTypeCosts = value; }
    	}
        [NonSerialized]
    	protected ICollection<Visit> visits;
    
    	public virtual ICollection<Visit> Visits
    	{
     		get { return visits; }
     		set { visits = value; }
    	}
        [NonSerialized]
    	protected ICollection<VisitTemplate> visitTemplates;
    
    	public virtual ICollection<VisitTemplate> VisitTemplates
    	{
     		get { return visitTemplates; }
     		set { visitTemplates = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
