//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class HealthGroup
    {
        public HealthGroup()
        {
            this.PersonHealthGroups = new HashSet<PersonHealthGroup>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
    
        [NonSerialized]
    	private ICollection<PersonHealthGroup> personHealthGroups;
    
    	public virtual ICollection<PersonHealthGroup> PersonHealthGroups
    	{
     		get { return personHealthGroups; }
     		set { personHealthGroups = value; }
    	}
    }
}
