
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Core.Data
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class IdentityDocumentType : ICloneable
{

    public IdentityDocumentType()
    {

        this.PersonIdentityDocuments = new HashSet<PersonIdentityDocument>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Options { get; set; }

    public System.DateTime BeginDateTime { get; set; }

    public System.DateTime EndDateTime { get; set; }

    public string DocSeria { get; set; }

    public string DocNumber { get; set; }




    [NonSerialized]
    	protected ICollection<PersonIdentityDocument> personIdentityDocuments;
    
    	public virtual ICollection<PersonIdentityDocument> PersonIdentityDocuments
    	{
     		get { return personIdentityDocuments; }
     		set { personIdentityDocuments = value; }
    	}


	public object Clone()
	{
		return MemberwiseClone();
	}
}

}
