//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class InsuranceDocument : ICloneable
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int InsuranceCompanyId { get; set; }
        public int InsuranceDocumentTypeId { get; set; }
        public string Series { get; set; }
        public string Number { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.DateTime> DeleteDateTime { get; set; }
    
        [NonSerialized]
    	protected InsuranceCompany insuranceCompany;
    
    	public virtual InsuranceCompany InsuranceCompany
    	{
     		get { return insuranceCompany; }
     		set { insuranceCompany = value; }
    	}
        [NonSerialized]
    	protected InsuranceDocumentType insuranceDocumentType;
    
    	public virtual InsuranceDocumentType InsuranceDocumentType
    	{
     		get { return insuranceDocumentType; }
     		set { insuranceDocumentType = value; }
    	}
        [NonSerialized]
    	protected Person person;
    
    	public virtual Person Person
    	{
     		get { return person; }
     		set { person = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
