//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class MaritalStatus : ICloneable
    {
        public MaritalStatus()
        {
            this.PersonMaritalStatuses = new HashSet<PersonMaritalStatus>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        [NonSerialized]
    	protected ICollection<PersonMaritalStatus> personMaritalStatuses;
    
    	public virtual ICollection<PersonMaritalStatus> PersonMaritalStatuses
    	{
     		get { return personMaritalStatuses; }
     		set { personMaritalStatuses = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
