
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Core.Data
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class MKB : ICloneable
{

    public MKB()
    {

        this.MKB1 = new HashSet<MKB>();

        this.Records = new HashSet<Record>();

    }


    public int Id { get; set; }

    public Nullable<int> GroupId { get; set; }

    public Nullable<int> ParentId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }




    [NonSerialized]
    	protected ICollection<MKB> mKB1;
    
    	public virtual ICollection<MKB> MKB1
    	{
     		get { return mKB1; }
     		set { mKB1 = value; }
    	}

    [NonSerialized]
    	protected MKB mKB2;
    
    	public virtual MKB MKB2
    	{
     		get { return mKB2; }
     		set { mKB2 = value; }
    	}

    [NonSerialized]
    	protected MKBGroup mKBGroup;
    
    	public virtual MKBGroup MKBGroup
    	{
     		get { return mKBGroup; }
     		set { mKBGroup = value; }
    	}


    [NonSerialized]
    	protected ICollection<Record> records;
    
    	public virtual ICollection<Record> Records
    	{
     		get { return records; }
     		set { records = value; }
    	}


	public object Clone()
	{
		return MemberwiseClone();
	}
}

}
