//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    public partial class Okato
    {
        public int Id { get; set; }
        public string CodeOKATO { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string CodeOKTMO { get; set; }
        public string RegionCode { get; set; }
    }
}
