//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Org
    {
        public Org()
        {
            this.Assignments = new HashSet<Assignment>();
            this.PersonSocialStatuses = new HashSet<PersonSocialStatus>();
            this.RecordContracts = new HashSet<RecordContract>();
            this.Visits = new HashSet<Visit>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public bool IsLpu { get; set; }
        public bool UseInContract { get; set; }
    
        [NonSerialized]
    	private ICollection<Assignment> assignments;
    
    	public virtual ICollection<Assignment> Assignments
    	{
     		get { return assignments; }
     		set { assignments = value; }
    	}
        [NonSerialized]
    	private ICollection<PersonSocialStatus> personSocialStatuses;
    
    	public virtual ICollection<PersonSocialStatus> PersonSocialStatuses
    	{
     		get { return personSocialStatuses; }
     		set { personSocialStatuses = value; }
    	}
        [NonSerialized]
    	private ICollection<RecordContract> recordContracts;
    
    	public virtual ICollection<RecordContract> RecordContracts
    	{
     		get { return recordContracts; }
     		set { recordContracts = value; }
    	}
        [NonSerialized]
    	private ICollection<Visit> visits;
    
    	public virtual ICollection<Visit> Visits
    	{
     		get { return visits; }
     		set { visits = value; }
    	}
    }
}
