//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class PermissionGroupMembership
    {
        public int Id { get; set; }
        public int PermissionId { get; set; }
        public int GroupId { get; set; }
    
        [NonSerialized]
    	private PermissionGroup permissionGroup;
    
    	public virtual PermissionGroup PermissionGroup
    	{
     		get { return permissionGroup; }
     		set { permissionGroup = value; }
    	}
        [NonSerialized]
    	private Permission permission;
    
    	public virtual Permission Permission
    	{
     		get { return permission; }
     		set { permission = value; }
    	}
    }
}
