//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class PermissionGroup
    {
        public PermissionGroup()
        {
            this.PermissionGroupMemberships = new HashSet<PermissionGroupMembership>();
            this.PermissionGroups1 = new HashSet<PermissionGroup>();
            this.UserPermisionGroups = new HashSet<UserPermisionGroup>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        [NonSerialized]
    	private ICollection<PermissionGroupMembership> permissionGroupMemberships;
    
    	public virtual ICollection<PermissionGroupMembership> PermissionGroupMemberships
    	{
     		get { return permissionGroupMemberships; }
     		set { permissionGroupMemberships = value; }
    	}
        [NonSerialized]
    	private ICollection<PermissionGroup> permissionGroups1;
    
    	public virtual ICollection<PermissionGroup> PermissionGroups1
    	{
     		get { return permissionGroups1; }
     		set { permissionGroups1 = value; }
    	}
        [NonSerialized]
    	private PermissionGroup permissionGroup1;
    
    	public virtual PermissionGroup PermissionGroup1
    	{
     		get { return permissionGroup1; }
     		set { permissionGroup1 = value; }
    	}
        [NonSerialized]
    	private ICollection<UserPermisionGroup> userPermisionGroups;
    
    	public virtual ICollection<UserPermisionGroup> UserPermisionGroups
    	{
     		get { return userPermisionGroups; }
     		set { userPermisionGroups = value; }
    	}
    }
}
