//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class PersonStaff
    {
        public PersonStaff()
        {
            this.CommissionMembers = new HashSet<CommissionMember>();
            this.RecordContractItems = new HashSet<RecordContractItem>();
            this.RecordContracts = new HashSet<RecordContract>();
            this.RecordMembers = new HashSet<RecordMember>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int BranchId { get; set; }
        public int StaffId { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
    
        [NonSerialized]
    	private Branch branch;
    
    	public virtual Branch Branch
    	{
     		get { return branch; }
     		set { branch = value; }
    	}
        [NonSerialized]
    	private ICollection<CommissionMember> commissionMembers;
    
    	public virtual ICollection<CommissionMember> CommissionMembers
    	{
     		get { return commissionMembers; }
     		set { commissionMembers = value; }
    	}
        [NonSerialized]
    	private Person person;
    
    	public virtual Person Person
    	{
     		get { return person; }
     		set { person = value; }
    	}
        [NonSerialized]
    	private Staff staff;
    
    	public virtual Staff Staff
    	{
     		get { return staff; }
     		set { staff = value; }
    	}
        [NonSerialized]
    	private ICollection<RecordContractItem> recordContractItems;
    
    	public virtual ICollection<RecordContractItem> RecordContractItems
    	{
     		get { return recordContractItems; }
     		set { recordContractItems = value; }
    	}
        [NonSerialized]
    	private ICollection<RecordContract> recordContracts;
    
    	public virtual ICollection<RecordContract> RecordContracts
    	{
     		get { return recordContracts; }
     		set { recordContracts = value; }
    	}
        [NonSerialized]
    	private ICollection<RecordMember> recordMembers;
    
    	public virtual ICollection<RecordMember> RecordMembers
    	{
     		get { return recordMembers; }
     		set { recordMembers = value; }
    	}
    }
}
