//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Core.Data
{
    public partial class PersonSocialStatus
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int SocialStatusTypeId { get; set; }
        public string Office { get; set; }
        public Nullable<int> OrgId { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
    
        public virtual Org Org { get; set; }
        public virtual SocialStatusType SocialStatusType { get; set; }
        public virtual Person Person { get; set; }
    }
}
