//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class PersonOuterDocument
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int OuterDocumentTypeId { get; set; }
        public int DocumentId { get; set; }
    
        [NonSerialized]
    	private Document document;
    
    	public virtual Document Document
    	{
     		get { return document; }
     		set { document = value; }
    	}
        [NonSerialized]
    	private OuterDocumentType outerDocumentType;
    
    	public virtual OuterDocumentType OuterDocumentType
    	{
     		get { return outerDocumentType; }
     		set { outerDocumentType = value; }
    	}
        [NonSerialized]
    	private Person person;
    
    	public virtual Person Person
    	{
     		get { return person; }
     		set { person = value; }
    	}
    }
}
