//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class PersonAddress : ICloneable
    {
        public PersonAddress()
        {
            this.PersonTalons = new HashSet<PersonTalon>();
            this.CommissionProtocols = new HashSet<CommissionProtocol>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int AddressTypeId { get; set; }
        public int OkatoId { get; set; }
        public string UserText { get; set; }
        public string House { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public string Building { get; set; }
        public string Apartment { get; set; }
    
        [NonSerialized]
    	protected AddressType addressType;
    
    	public virtual AddressType AddressType
    	{
     		get { return addressType; }
     		set { addressType = value; }
    	}
        [NonSerialized]
    	protected Okato okato;
    
    	public virtual Okato Okato
    	{
     		get { return okato; }
     		set { okato = value; }
    	}
        [NonSerialized]
    	protected Person person;
    
    	public virtual Person Person
    	{
     		get { return person; }
     		set { person = value; }
    	}
        [NonSerialized]
    	protected ICollection<PersonTalon> personTalons;
    
    	public virtual ICollection<PersonTalon> PersonTalons
    	{
     		get { return personTalons; }
     		set { personTalons = value; }
    	}
        [NonSerialized]
    	protected ICollection<CommissionProtocol> commissionProtocols;
    
    	public virtual ICollection<CommissionProtocol> CommissionProtocols
    	{
     		get { return commissionProtocols; }
     		set { commissionProtocols = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
