
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Core.Data
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class PersonEducation : ICloneable
{

    public int Id { get; set; }

    public int PersonId { get; set; }

    public int EducationId { get; set; }

    public System.DateTime BeginDateTime { get; set; }

    public System.DateTime EndDateTime { get; set; }



    [NonSerialized]
    	protected Education education;
    
    	public virtual Education Education
    	{
     		get { return education; }
     		set { education = value; }
    	}

    [NonSerialized]
    	protected Person person;
    
    	public virtual Person Person
    	{
     		get { return person; }
     		set { person = value; }
    	}


	public object Clone()
	{
		return MemberwiseClone();
	}
}

}
