//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class PersonRelative : ICloneable
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int RelativeId { get; set; }
        public int RelativeRelationshipId { get; set; }
        public bool IsRepresentative { get; set; }
    
        [NonSerialized]
    	protected Person person;
    
    	public virtual Person Person
    	{
     		get { return person; }
     		set { person = value; }
    	}
        [NonSerialized]
    	protected Person person1;
    
    	public virtual Person Person1
    	{
     		get { return person1; }
     		set { person1 = value; }
    	}
        [NonSerialized]
    	protected RelativeRelationship relativeRelationship;
    
    	public virtual RelativeRelationship RelativeRelationship
    	{
     		get { return relativeRelationship; }
     		set { relativeRelationship = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
