//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordEquipment
    {
        public int Id { get; set; }
        public int RecordId { get; set; }
        public int EquipmentId { get; set; }
        public Nullable<System.DateTime> BeginDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public double Duration { get; set; }
    
        public virtual Eqiupment Eqiupment { get; set; }
        public virtual Record Record { get; set; }
    }
}
