
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Core.Data
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class RecordTypeEditor : ICloneable
{

    public int Id { get; set; }

    public int RecordTypeId { get; set; }

    public string Editor { get; set; }

    public bool HasDocuments { get; set; }

    public bool HasDICOM { get; set; }

    public bool UseEquipments { get; set; }



    [NonSerialized]
    	protected RecordType recordType;
    
    	public virtual RecordType RecordType
    	{
     		get { return recordType; }
     		set { recordType = value; }
    	}


	public object Clone()
	{
		return MemberwiseClone();
	}
}

}
