//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class RecordTypeRolePermission : ICloneable
    {
        public RecordTypeRolePermission()
        {
            this.RecordMembers = new HashSet<RecordMember>();
        }
    
        public int Id { get; set; }
        public int RecordTypeId { get; set; }
        public int RecordTypeMemberRoleId { get; set; }
        public int PermissionId { get; set; }
        public bool IsSign { get; set; }
        public bool IsRequired { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
    
        [NonSerialized]
    	protected RecordTypeRole recordTypeRole;
    
    	public virtual RecordTypeRole RecordTypeRole
    	{
     		get { return recordTypeRole; }
     		set { recordTypeRole = value; }
    	}
        [NonSerialized]
    	protected ICollection<RecordMember> recordMembers;
    
    	public virtual ICollection<RecordMember> RecordMembers
    	{
     		get { return recordMembers; }
     		set { recordMembers = value; }
    	}
        [NonSerialized]
    	protected RecordType recordType;
    
    	public virtual RecordType RecordType
    	{
     		get { return recordType; }
     		set { recordType = value; }
    	}
        [NonSerialized]
    	protected Permission permission;
    
    	public virtual Permission Permission
    	{
     		get { return permission; }
     		set { permission = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
