//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordDocument
    {
        public int Id { get; set; }
        public Nullable<int> AssignmentId { get; set; }
        public Nullable<int> RecordId { get; set; }
        public int DocumentId { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Assignment Assignment { get; set; }
        public virtual Record Record { get; set; }
    }
}
