//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordTypeEditor
    {
        public int Id { get; set; }
        public int RecordTypeId { get; set; }
        public bool HasDocuments { get; set; }
        public bool HasDICOM { get; set; }
    
        public virtual RecordType RecordType { get; set; }
    }
}
