//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class RecordDocument : ICloneable
    {
        public int Id { get; set; }
        public Nullable<int> AssignmentId { get; set; }
        public Nullable<int> RecordId { get; set; }
        public int DocumentId { get; set; }
    
        [NonSerialized]
    	protected Document document;
    
    	public virtual Document Document
    	{
     		get { return document; }
     		set { document = value; }
    	}
        [NonSerialized]
    	protected Assignment assignment;
    
    	public virtual Assignment Assignment
    	{
     		get { return assignment; }
     		set { assignment = value; }
    	}
        [NonSerialized]
    	protected Record record;
    
    	public virtual Record Record
    	{
     		get { return record; }
     		set { record = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
