//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class RecordContract : ICloneable
    {
        public RecordContract()
        {
            this.CommissionProtocols = new HashSet<CommissionProtocol>();
            this.MedicalHelpTypes = new HashSet<MedicalHelpType>();
            this.PersonTalons = new HashSet<PersonTalon>();
            this.RecordContractItems = new HashSet<RecordContractItem>();
            this.RecordContractLimits = new HashSet<RecordContractLimit>();
            this.Visits = new HashSet<Visit>();
            this.VisitTemplates = new HashSet<VisitTemplate>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Number { get; set; }
        public string ContractName { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public int FinancingSourceId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> ConsumerId { get; set; }
        public Nullable<int> OrgId { get; set; }
        public string OrgDetails { get; set; }
        public double ContractCost { get; set; }
        public int PaymentTypeId { get; set; }
        public string TransactionNumber { get; set; }
        public string TransactionDate { get; set; }
        public int Priority { get; set; }
        public string Options { get; set; }
        public System.DateTime InDateTime { get; set; }
        public int InUserId { get; set; }
    
        [NonSerialized]
    	protected ICollection<CommissionProtocol> commissionProtocols;
    
    	public virtual ICollection<CommissionProtocol> CommissionProtocols
    	{
     		get { return commissionProtocols; }
     		set { commissionProtocols = value; }
    	}
        [NonSerialized]
    	protected FinancingSource financingSource;
    
    	public virtual FinancingSource FinancingSource
    	{
     		get { return financingSource; }
     		set { financingSource = value; }
    	}
        [NonSerialized]
    	protected ICollection<MedicalHelpType> medicalHelpTypes;
    
    	public virtual ICollection<MedicalHelpType> MedicalHelpTypes
    	{
     		get { return medicalHelpTypes; }
     		set { medicalHelpTypes = value; }
    	}
        [NonSerialized]
    	protected PaymentType paymentType;
    
    	public virtual PaymentType PaymentType
    	{
     		get { return paymentType; }
     		set { paymentType = value; }
    	}
        [NonSerialized]
    	protected Person person;
    
    	public virtual Person Person
    	{
     		get { return person; }
     		set { person = value; }
    	}
        [NonSerialized]
    	protected Person person1;
    
    	public virtual Person Person1
    	{
     		get { return person1; }
     		set { person1 = value; }
    	}
        [NonSerialized]
    	protected PersonStaff personStaff;
    
    	public virtual PersonStaff PersonStaff
    	{
     		get { return personStaff; }
     		set { personStaff = value; }
    	}
        [NonSerialized]
    	protected ICollection<PersonTalon> personTalons;
    
    	public virtual ICollection<PersonTalon> PersonTalons
    	{
     		get { return personTalons; }
     		set { personTalons = value; }
    	}
        [NonSerialized]
    	protected ICollection<RecordContractItem> recordContractItems;
    
    	public virtual ICollection<RecordContractItem> RecordContractItems
    	{
     		get { return recordContractItems; }
     		set { recordContractItems = value; }
    	}
        [NonSerialized]
    	protected ICollection<RecordContractLimit> recordContractLimits;
    
    	public virtual ICollection<RecordContractLimit> RecordContractLimits
    	{
     		get { return recordContractLimits; }
     		set { recordContractLimits = value; }
    	}
        [NonSerialized]
    	protected ICollection<Visit> visits;
    
    	public virtual ICollection<Visit> Visits
    	{
     		get { return visits; }
     		set { visits = value; }
    	}
        [NonSerialized]
    	protected ICollection<VisitTemplate> visitTemplates;
    
    	public virtual ICollection<VisitTemplate> VisitTemplates
    	{
     		get { return visitTemplates; }
     		set { visitTemplates = value; }
    	}
        [NonSerialized]
    	protected Org org;
    
    	public virtual Org Org
    	{
     		get { return org; }
     		set { org = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
