//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class RecordContractItem : ICloneable
    {
        public int Id { get; set; }
        public int RecordContractId { get; set; }
        public Nullable<int> AssignmentId { get; set; }
        public int RecordTypeId { get; set; }
        public int Count { get; set; }
        public double Cost { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<int> Appendix { get; set; }
        public int InUserId { get; set; }
        public System.DateTime InDateTime { get; set; }
    
        [NonSerialized]
    	protected PersonStaff personStaff;
    
    	public virtual PersonStaff PersonStaff
    	{
     		get { return personStaff; }
     		set { personStaff = value; }
    	}
        [NonSerialized]
    	protected RecordContract recordContract;
    
    	public virtual RecordContract RecordContract
    	{
     		get { return recordContract; }
     		set { recordContract = value; }
    	}
        [NonSerialized]
    	protected RecordType recordType;
    
    	public virtual RecordType RecordType
    	{
     		get { return recordType; }
     		set { recordType = value; }
    	}
        [NonSerialized]
    	protected Assignment assignment;
    
    	public virtual Assignment Assignment
    	{
     		get { return assignment; }
     		set { assignment = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
