
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Core.Data
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class RecordTypeRole : ICloneable
{

    public RecordTypeRole()
    {

        this.RecordTypeRolePermissions = new HashSet<RecordTypeRolePermission>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string ShortName { get; set; }

    public string Options { get; set; }




    [NonSerialized]
    	protected ICollection<RecordTypeRolePermission> recordTypeRolePermissions;
    
    	public virtual ICollection<RecordTypeRolePermission> RecordTypeRolePermissions
    	{
     		get { return recordTypeRolePermissions; }
     		set { recordTypeRolePermissions = value; }
    	}


	public object Clone()
	{
		return MemberwiseClone();
	}
}

}
