//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    public partial class RecordContractLimit
    {
        public int Id { get; set; }
        public int RecordContractId { get; set; }
        public int RecordTypeId { get; set; }
        public int Count { get; set; }
    
        public virtual RecordContract RecordContract { get; set; }
        public virtual RecordType RecordType { get; set; }
    }
}
