//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class RelativeRelationshipConnection : ICloneable
    {
        public int Id { get; set; }
        public int ParentRelationshipId { get; set; }
        public int ChildRelationshipId { get; set; }
    
        [NonSerialized]
    	protected RelativeRelationship relativeRelationship;
    
    	public virtual RelativeRelationship RelativeRelationship
    	{
     		get { return relativeRelationship; }
     		set { relativeRelationship = value; }
    	}
        [NonSerialized]
    	protected RelativeRelationship relativeRelationship1;
    
    	public virtual RelativeRelationship RelativeRelationship1
    	{
     		get { return relativeRelationship1; }
     		set { relativeRelationship1 = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
