
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Core.Data
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class ScheduleItem : ICloneable
{

    public int Id { get; set; }

    public int RoomId { get; set; }

    public Nullable<int> RecordTypeId { get; set; }

    public int DayOfWeek { get; set; }

    public System.DateTime BeginDate { get; set; }

    public System.DateTime EndDate { get; set; }

    public System.TimeSpan StartTime { get; set; }

    public System.TimeSpan EndTime { get; set; }



    [NonSerialized]
    	protected Room room;
    
    	public virtual Room Room
    	{
     		get { return room; }
     		set { room = value; }
    	}

    [NonSerialized]
    	protected RecordType recordType;
    
    	public virtual RecordType RecordType
    	{
     		get { return recordType; }
     		set { recordType = value; }
    	}


	public object Clone()
	{
		return MemberwiseClone();
	}
}

}
