//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Core.Data
{
    public partial class ScheduleItem
    {
        public int Id { get; set; }
        public int RoomId { get; set; }
        public Nullable<int> RecordTypeId { get; set; }
        public int DayOfWeek { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual RecordType RecordType { get; set; }
    }
}
