//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class SocialStatusType : ICloneable
    {
        public SocialStatusType()
        {
            this.PersonSocialStatuses = new HashSet<PersonSocialStatus>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public bool NeedPlace { get; set; }
    
        [NonSerialized]
    	protected ICollection<PersonSocialStatus> personSocialStatuses;
    
    	public virtual ICollection<PersonSocialStatus> PersonSocialStatuses
    	{
     		get { return personSocialStatuses; }
     		set { personSocialStatuses = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
