//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class StaffCategory : ICloneable
    {
        public StaffCategory()
        {
            this.Staffs = new HashSet<Staff>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        [NonSerialized]
    	protected ICollection<Staff> staffs;
    
    	public virtual ICollection<Staff> Staffs
    	{
     		get { return staffs; }
     		set { staffs = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
