
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Core.Data
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class Staff : ICloneable
{

    public Staff()
    {

        this.CommissionMembers = new HashSet<CommissionMember>();

        this.PersonStaffs = new HashSet<PersonStaff>();

    }


    public int Id { get; set; }

    public Nullable<int> ParentId { get; set; }

    public string Name { get; set; }

    public string ShortName { get; set; }

    public int CategoryId { get; set; }

    public bool IsSenior { get; set; }




    [NonSerialized]
    	protected ICollection<CommissionMember> commissionMembers;
    
    	public virtual ICollection<CommissionMember> CommissionMembers
    	{
     		get { return commissionMembers; }
     		set { commissionMembers = value; }
    	}


    [NonSerialized]
    	protected ICollection<PersonStaff> personStaffs;
    
    	public virtual ICollection<PersonStaff> PersonStaffs
    	{
     		get { return personStaffs; }
     		set { personStaffs = value; }
    	}

    [NonSerialized]
    	protected StaffCategory staffCategory;
    
    	public virtual StaffCategory StaffCategory
    	{
     		get { return staffCategory; }
     		set { staffCategory = value; }
    	}


	public object Clone()
	{
		return MemberwiseClone();
	}
}

}
