//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Unit : ICloneable
    {
        public Unit()
        {
            this.RecordTypeUnits = new HashSet<RecordTypeUnit>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public bool OnlyForMedWare { get; set; }
    
        [NonSerialized]
    	protected ICollection<RecordTypeUnit> recordTypeUnits;
    
    	public virtual ICollection<RecordTypeUnit> RecordTypeUnits
    	{
     		get { return recordTypeUnits; }
     		set { recordTypeUnits = value; }
    	}
    
    	public object Clone()
    	{
    		return MemberwiseClone();
    	}
    }
}
