//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class UserMessage
    {
        public int Id { get; set; }
        public int SenderUserId { get; set; }
        public int RecieverUserId { get; set; }
        public System.DateTime SendDateTime { get; set; }
        public System.DateTime OutDateTime { get; set; }
        public System.DateTime ReadDateTime { get; set; }
        public string MessageText { get; set; }
        public int MessageData { get; set; }
        public int UserMessageTypeId { get; set; }
    
        [NonSerialized]
    	private User user;
    
    	public virtual User User
    	{
     		get { return user; }
     		set { user = value; }
    	}
        [NonSerialized]
    	private User user1;
    
    	public virtual User User1
    	{
     		get { return user1; }
     		set { user1 = value; }
    	}
        [NonSerialized]
    	private UserMessageType userMessageType;
    
    	public virtual UserMessageType UserMessageType
    	{
     		get { return userMessageType; }
     		set { userMessageType = value; }
    	}
    }
}
