//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int Id { get; set; }
        public int AssignmentTypeId { get; set; }
        public int PatientId { get; set; }
        public int AssignUserId { get; set; }
        public System.DateTime AssignDateTime { get; set; }
        public bool IsCompleted { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CancelDateTime { get; set; }
        public Nullable<int> CancelUserId { get; set; }
    
        public virtual User AssignedUser { get; set; }
        public virtual AssignmentType AssignmentType { get; set; }
        public virtual User CancelledUser { get; set; }
        public virtual Person Patient { get; set; }
    }
}
