//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionDecision
    {
        public int Id { get; set; }
        public int CommissionProtocolId { get; set; }
        public int CommissionMemberId { get; set; }
        public Nullable<int> DecisionId { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public bool IsOfficial { get; set; }
        public bool IsAsked { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DecisionInDateTime { get; set; }
    
        public virtual CommissionMember CommissionMember { get; set; }
        public virtual Decision Decision { get; set; }
        public virtual CommissionProtocol CommissionProtocol { get; set; }
    }
}
