//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    public partial class CommissionDecisionsLink
    {
        public int Id { get; set; }
        public int CommissionTypeId { get; set; }
        public int CommissionTypeMemberId { get; set; }
        public int DecisionId { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
    
        public virtual CommissionMemberType CommissionMemberType { get; set; }
        public virtual CommissionType CommissionType { get; set; }
        public virtual Decision Decision { get; set; }
    }
}
