//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionProtocol
    {
        public CommissionProtocol()
        {
            this.CommissionDecisions = new HashSet<CommissionDecision>();
            this.CommissionProtocolMembers = new HashSet<CommissionProtocolMember>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int CommissionTypeId { get; set; }
        public Nullable<int> DecisionId { get; set; }
        public Nullable<int> DocumentNumber { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<CommissionDecision> CommissionDecisions { get; set; }
        public virtual ICollection<CommissionProtocolMember> CommissionProtocolMembers { get; set; }
        public virtual Person Person { get; set; }
    }
}
