//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.PersonNationalities = new HashSet<PersonNationality>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public bool IsDefaultNationality { get; set; }
    
        public virtual ICollection<PersonNationality> PersonNationalities { get; set; }
    }
}
