//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisabilityType
    {
        public DisabilityType()
        {
            this.PersonDisabilities = new HashSet<PersonDisability>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual ICollection<PersonDisability> PersonDisabilities { get; set; }
    }
}
