//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionPlace
    {
        public ExecutionPlace()
        {
            this.VisitOutcomes = new HashSet<VisitOutcome>();
            this.VisitResults = new HashSet<VisitResult>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string UseName { get; set; }
    
        public virtual ICollection<VisitOutcome> VisitOutcomes { get; set; }
        public virtual ICollection<VisitResult> VisitResults { get; set; }
    }
}
