//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityDocumentType
    {
        public IdentityDocumentType()
        {
            this.PersonIdentityDocuments = new HashSet<PersonIdentityDocument>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PersonIdentityDocument> PersonIdentityDocuments { get; set; }
    }
}
