//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;

    public partial class PermissionLink
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int ChildId { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual Permission Permission1 { get; set; }
    }
}
