//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.PermissionLinks = new HashSet<PermissionLink>();
            this.PermissionLinks1 = new HashSet<PermissionLink>();
            this.UserPermissions = new HashSet<UserPermission>();
            this.RecordTypeRolePermissions = new HashSet<RecordTypeRolePermission>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsGroup { get; set; }
        public bool ReadOnly { get; set; }
    
        public virtual ICollection<PermissionLink> PermissionLinks { get; set; }
        public virtual ICollection<PermissionLink> PermissionLinks1 { get; set; }
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
        public virtual ICollection<RecordTypeRolePermission> RecordTypeRolePermissions { get; set; }
    }
}
