//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonTalon
    {
        public PersonTalon()
        {
            this.CommissionProtocols = new HashSet<CommissionProtocol>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public string TalonNumber { get; set; }
        public System.DateTime TalonDateTime { get; set; }
        public string MKB { get; set; }
        public int RecordContractId { get; set; }
        public Nullable<int> MedicalHelpTypeId { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<CommissionProtocol> CommissionProtocols { get; set; }
        public virtual MedicalHelpType MedicalHelpType { get; set; }
        public virtual RecordContract RecordContract { get; set; }
        public virtual Person Person { get; set; }
    }
}
