//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonStaff
    {
        public PersonStaff()
        {
            this.CommissionMembers = new HashSet<CommissionMember>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int BranchId { get; set; }
        public int StaffId { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public bool IsSign { get; set; }
        public bool IsActing { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<CommissionMember> CommissionMembers { get; set; }
        public virtual Person Person { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
