//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Records = new HashSet<Record>();
            this.ScheduleItems = new HashSet<ScheduleItem>();
            this.Assignments = new HashSet<Assignment>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Record> Records { get; set; }
        public virtual ICollection<ScheduleItem> ScheduleItems { get; set; }
        public virtual ICollection<Assignment> Assignments { get; set; }
    }
}
