//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDay
    {
        public ScheduleDay()
        {
            this.ScheduleDayItems = new HashSet<ScheduleDayItem>();
        }
    
        public int Id { get; set; }
        public int RoomId { get; set; }
        public int RecordTypeId { get; set; }
        public int DayOfWeek { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual ICollection<ScheduleDayItem> ScheduleDayItems { get; set; }
        public virtual RecordType RecordType { get; set; }
    }
}
