//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessage
    {
        public int Id { get; set; }
        public int SenderUserId { get; set; }
        public int RecieverUserId { get; set; }
        public System.DateTime SendDateTime { get; set; }
        public System.DateTime OutDateTime { get; set; }
        public System.DateTime ReadDateTime { get; set; }
        public string MessageText { get; set; }
        public int MessageData { get; set; }
        public int UserMessageTypeId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual UserMessageType UserMessageType { get; set; }
    }
}
