//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;

    public partial class Visit
    {
        public int Id { get; set; }
        public int VisitTypeId { get; set; }
        public int PersonId { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public int UrgentlyId { get; set; }
        public int FinancingSourceId { get; set; }
        public int ContractId { get; set; }
        public int SentLPUId { get; set; }
        public string OKATO { get; set; }
        public string MKB { get; set; }
        public Nullable<int> VisitResultId { get; set; }
        public Nullable<int> VisitOutcomeId { get; set; }
        public string Note { get; set; }
        public double TotalCost { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
    
        public virtual Org Org { get; set; }
        public virtual VisitOutcome VisitOutcome { get; set; }
        public virtual VisitResult VisitResult { get; set; }
        public virtual FinancingSource FinancingSource { get; set; }
        public virtual Person Person { get; set; }
        public virtual RecordContract RecordContract { get; set; }
    }
}
